server:
  port: 8889
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/oldx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: FebsHikariCP
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: oldx #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
