server:
  port: 8889
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/oldx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: FebsHikariCP
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: oldx #JWT加解密使用的密钥
  expiration: 302400 #JWT的超期限时间
  tokenHead: Bearer  #JWT负载中拿到开头

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/cc/oldx/mbg/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cc.oldx.mbg.domain
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
oldx:
  showsql: true

